package org.firstinspires.ftc.teamcode.ETCHardware;

public interface ETCConstants {

    int NEVEREST_20_CPR = 560;
    int NEVEREST_40_CPR = 1120;
    int NEVEREST_60_CPR = 1680;

    int CPR_LIFT_MOTOR = NEVEREST_40_CPR;
    int SHOOTER_CPR = 1315;

    double STOPPER_CLOSE_POSITION = 0.12;
    double STOPPER_OPEN_POSITION = 0.42;

    int AUTONOMOUS_TENSION_POSITION = -275;
    int BLUE_AUTONOMOUS_TENSION_POSITION = -175;
    int ALLIANCE_AUTONOMOUS_TENSION = -4750;
    int ZERO_TENSION_POSITION = -100;
    int LOW_TENSION_POSITION = -500;
    int MEDIUM_TENSION_POSITION = -1500;
    int HIGH_TENSION_POSITION = -3000;
    int VERY_HIGH_TENSION_POSITION = -4500;

    double SPEED_GEAR_RATIO_FACTOR = 0.80; // (64/84)
    double MOVE_TO_WHITE_TAPE_POWER = 0.20 * SPEED_GEAR_RATIO_FACTOR;

    double POSITION_2_DELAY_PARKING_TIME = 25000;
}
